branches:
  except:
    - appveyor
    - circleci

language: cpp

os:
  - linux
  - osx

compiler:
  - clang

osx_image: xcode9.2

dist: xenial

sudo: true

install:
  - pushd ci
  - ./install_deps.sh
  - popd

before_script:
  - export BUILD_DIR="build"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DEPLOY_DOCS="true"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CMAKE_FLAGS="$CMAKE_FLAGS -DTINYSPLINE_WITH_PHP=FALSE -DTINYSPLINE_WITH_RUBY=FALSE"; fi;

script:
  - pushd ci
  - ./compile.sh
  - ./deploy_docs.sh
  - popd
